### ISSUE TITLE
疑似log4j的bug

### ISSUE THREAD

**Issue by k4n5ha0** [murphysecurity/murphysec#10]
![image](https://user-images.githubusercontent.com/22064977/162658093-6540be18-46ab-4fd9-b9c8-72d9635fb678.png)
第一次提示升级到2.13第二次才会升级到2.17，可能是bug，理论上应该一次性升级到2.17
![image](https://user-images.githubusercontent.com/22064977/162658882-70793b83-f0c0-471b-8f80-064764e7e842.png)

**Comment by chncaption** [comment]
感谢反馈，我们马上看下
