### ISSUE TITLE
idea插件的可用性增强

### ISSUE THREAD

**Issue by k4n5ha0** [murphysecurity/murphysec#11]
![image](https://user-images.githubusercontent.com/22064977/162659579-3e95c2b1-b4e0-40c8-bee1-df9b8a66d566.png)
建议右侧设置为可读，这样用户就可以直接复制进行搜索并进行定位

**Comment by CN-You** [comment]
收到反馈，JetBrains 的 IDE 展示内容默认无法复制，我们可以针对需要复制的内容做单独处理，您这边主要想复制哪些信息呢？

**Comment by k4n5ha0** [comment]
> 收到反馈，JetBrains 的 IDE 展示内容默认无法复制，我们可以针对需要复制的内容做单独处理，您这边主要想复制哪些信息呢？

主要还是jar包的信息，因为开发人员修改依赖有时候牵一发而动全身，如果能复制并直接放到浏览器内搜索jar的名字就会很方便

**Comment by CN-You** [comment]
OK 计划在 IDE 插件下个版本支持

**Comment by CN-You** [comment]
您好，昨天 IDE 插件发布了3.0.0版本，支持了右侧组件和漏洞内容的复制。可以直接在 IDE 插件市场中进行升级
