### ISSUE TITLE
ui设计增强一处

### ISSUE THREAD

**Issue by k4n5ha0** [murphysecurity/murphysec#12]
![image](https://user-images.githubusercontent.com/22064977/162664841-2b178a7c-afa6-4221-81ea-48dc388113c8.png)
应该设置滚动框，否则无法看到下面的jar信息

**Comment by CN-You** [comment]
收到您的反馈，和 https://github.com/murphysecurity/murphysec/issues/8 是同一个问题

将在下个版本支持滚动

**Comment by CN-You** [comment]
插件2.0.7版本已经发布，增加了滚动条并且支持了 JetBrains IDE 2022.1版本

在 IDE 插件设置中可以直接进行更新
