### ISSUE TITLE
:bomb: `Bug`: 使用 3.0.1 时，输出到文件中的内容与控制台不同，比如文件中的内容比控制台少最后一段

### ISSUE THREAD

**Issue by xuxiaowei-com-cn** [murphysecurity/murphysec#126]
### What Happened?

使用 3.0.1 时，输出到文件中的内容与控制台不同，比如文件中的内容比控制台少最后一段

![NVIDIA_Share_eR88mWkdrs-](https://user-images.githubusercontent.com/46893436/218477735-dd6d9ced-e360-4482-a135-6f1bf14baa24.png)

### How to Reproduce?

扫描命令：murphysec-windows-amd64.exe scan "E:\IdeaProjects\xuxiaowei-cloud" --log-level info --write-log-to murphysec.log
项目：http://gitee.com/xuxiaowei-cloud/xuxiaowei-cloud

### Murphysec Version / Ide Plugin Version

3.0.1

**Comment by xuxiaowei-com-cn** [comment]
使用 --json 之后，能也把它输出吗？作为统计记录
![864f917dad3e1ee85b9e03803913758](https://user-images.githubusercontent.com/46893436/218602365-520b8fce-c8e2-44b9-960d-c9ac6a62b3e1.png)

**Comment by iseki0** [comment]
你可以使用 `--json` 启用 JSON 输出，不过这个JSON格式目前不保证稳定性（目前还没有过大改变）
`--log-level debug` 只用于输出日志

**Comment by xuxiaowei-com-cn** [comment]
使用 --json 的结果也是一样的，日志文件比控制台少最后的结果

**Comment by iseki0** [comment]
日志文件就是没有结果

> 使用 --json 的结果也是一样的，日志文件比控制台少最后的结果
