### ISSUE TITLE
建议按照优先级从高到低将漏洞进行排序

### ISSUE THREAD

**Issue by xuxiaowei-com-cn** [murphysecurity/murphysec#13]
![idea64_CpQSQbRbsO](https://user-images.githubusercontent.com/46893436/163411454-7b4c88e0-7fb1-47ed-9611-2f0d50c89601.png)

**Comment by chncaption** [comment]
收到，
哥，你这是一边直播一边提issues吗

**Comment by xuxiaowei-com-cn** [comment]
> 收到， 哥，你是一边直播一边提问题吗

碰巧而已
