### ISSUE TITLE
关于用户体验的小建议

### ISSUE THREAD

**Issue by CodeFromBicycleWarrior** [murphysecurity/murphysec#14]
- 如果“不小心”把插件从Sidebar移除了，就没办法再弄出来了，重新安装也不行（或许是我没找到正确的方法？可以在帮助文档中加一下找回的方法），没了菜单栏就不好看状态了
- 建议在控件合适的地方加上控制台超链接（ https://www.murphysec.com/control/project ），方便快速进入控制台

![image](https://user-images.githubusercontent.com/11723762/163424797-7e235b28-cc22-429b-b56b-75aca0fbd3ec.png)

![image](https://user-images.githubusercontent.com/11723762/163426038-e6718a6e-0c6c-48cb-ba7f-dc3e02cf77fe.png)

**Comment by CodeFromBicycleWarrior** [comment]
项目右键菜单上的“运行墨菲安全”点击了没有检测记录，我点了好多次都没有记录

![image](https://user-images.githubusercontent.com/11723762/163426813-9cbc1d08-5367-4eaa-89f5-19188f1b3566.png)

**Comment by CN-You** [comment]
非常好的建议和bug反馈👍，我们处理下这些问题，问题的解决情况我会及时在这里同步给您

**Comment by CN-You** [comment]
不小心将插件从 sidebar 移除的话，您可以点击`菜单栏` -> `View` -> `Tool Windows` -> `murphysec` ，插件将会重新出现在sidebar 上

<img width="781" alt="image" src="https://user-images.githubusercontent.com/99465056/163514422-f59b7c9d-a077-4e6d-b54c-3e1023fd07e6.png">

**Comment by CN-You** [comment]
右键“运行墨菲安全”，会进行检测，只不过因为插件从sidebar隐藏了，所以看不到检测结果，按照上面的方式在sidebar显示插件就OK了
