### ISSUE TITLE
安全检测结果的提示不准确

### ISSUE THREAD

**Issue by wangliguokaka** [murphysecurity/murphysec#15]
依赖配置如下，已经排除了protobuf-java，但是检测的结果还是提示有这个版本的jar包的漏洞
<dependency>
            <groupId>io.nats</groupId>
            <artifactId>java-nats-streaming</artifactId>
            <version>2.2.3</version>
            <exclusions>
                <exclusion>
                    <groupId>com.google.protobuf</groupId>
                    <artifactId>protobuf-java</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

检测结果如下：
![image](https://user-images.githubusercontent.com/17798088/163585380-866609b1-2f86-490b-a4f3-dbe63810eba6.png)

**Comment by chncaption** [comment]
收到，我们看下

**Comment by CN-You** [comment]
感谢您的反馈，暂时没有支持 exclusion，后续我们会处理这种情况

**Comment by wangliguokaka** [comment]
好的 感谢回复，期待越来越完善

**Comment by CN-You** [comment]
谢谢支持，后续支持后我会在这里及时同步给你

**Comment by wangliguokaka** [comment]
OK
