### ISSUE TITLE
:bomb: `Bug`: 使用IDEA最新版插件时，遇到了【插件认证不成功】的报错提示Bug

### ISSUE THREAD

**Issue by hanshou101** [murphysecurity/murphysec#162]
# 发生了什么
使用IDEA最新版插件时，遇到了【插件认证不成功】的报错提示Bug

# 环境
标准Win10
IDEA版本： IntelliJ 2021.2.2 Ultimate Edition
插件版本： 插件市场最新版（2023年5月14日-IDEA内置官方市场）

# Bug复现过程
1、从MarketPlace，下载【MurphySec】
2、然后，点击下方工具栏图标，并跟随引导，进入【插件设置】页面。
3、个人用户，点击【快速认证】。
4、此时网页弹出，新注册一个邮箱账号。注册成功后，点击网页【认证】按钮。
5、此时，返回到IDEA，发现【服务认证】下面的输入框，已经被自动填充了  若干星号字符。并且，插件弹出【认证成功】提示。
6、现在，点击下方工具栏窗口，【扫描】按钮。进行了一会儿之后，中止并提示【访问令牌已失效】。

# 后续排错过程
1、手动重新，在插件中，走【快速认证】了若干次，均未解决。
2、参照，插件的【解答文档】页面，没有相关内容。
3、检查，是否我自己的【代理】或【网络】问题，简单更改环境调试了一下，未果。
4、走Google和Baidu搜索，均未找到【访问令牌已失效】相关的回答帖子。
5、走GitHub的Issue，并未明显看到，类似的报错的历史Issue。

# 修复方式
1、后来，我尝试登录  MurphySec  官网，进入控制台。探索了一会儿。
2、发现了以下页面，都包含  【访问令牌Token】：[设置页面](https://www.murphysec.com/console/set/token)、[IDE集成的控制台说明页面](https://www.murphysec.com/console/detect-main?from=idea)
3、出于尝试心理，我手动将【访问令牌Token】，复制粘贴进了【插件设置】的【星号密码框】。
4、此时，再进行扫描，耐心等一会儿之后，发现扫描结果正常出来了。系统是86分。

**Comment by CN-You** [comment]
收到您的反馈，IDE插件支持快速认证和手动输入令牌两种认证方式，从问题描述看应该是【快速认证】没有成功。我们内部确认下，后续进展及时在这里同步
