### ISSUE TITLE
针对C/C++检测不准确

### ISSUE THREAD

**Issue by shangc1016** [murphysecurity/murphysec#17]
1、在使用cli命令`murphysec scan`的时候，有可选参数`--deep`，`--deep`参数的解释是上传源代码。请问加上`deep`参数之后，在远程做了什么，是否使用了某些针对代码混淆的算法？

2、对于C/C++项目，现在可以通过**文件级检测**的方式分析项目中包含的源码。对于不包含依赖源码C/C++项目的怎么解析呢？请问是通过正则表达式解析Makefile、CMake，还是使用CMake、Makefile的解析文本的代码？还是其他的什么方法？

3、下图是针对C语言的测试，目录下有curl-7.82.0以及nginx-1.18.0的源码。分别使用如下命令运行，加不加`--deep`参数似乎都没有正确分析依赖。

![image](https://note-img-1300721153.cos.ap-nanjing.myqcloud.com//md-imgimage-20220416230946406.png)

![image](https://note-img-1300721153.cos.ap-nanjing.myqcloud.com//md-imgimage-20220416230759016.png)

4、在文件`inspector/file_hash_scan.go`的`dirScan`函数中，得到目录下所有文件的路径，写入channel。请问在哈希的时候附带项目的目录结构时候有利于检测结果的准确性？

**Comment by iseki0** [comment]
> 4、在文件inspector/file_hash_scan.go的dirScan函数中，得到目录下所有文件的路径，写入channel。请问在哈希的时候附带项目的目录结构时候有利于检测结果的准确性？

没，那个只是把文件路径打进channel里，再另一个协程里算哈希而已

**Comment by chncaption** [comment]
@shangc1016 您好，c/c++相关的检测在我们的免费saas版本中暂不支持哈，所以您看到的检测结果展示是不完全的

**Comment by shangc1016** [comment]
感谢回复
