### ISSUE TITLE
:open_book: `Docs`: 

### ISSUE THREAD

**Issue by iron4rain** [murphysecurity/murphysec#174]
### What should be changed?

网站页面变更，超链接页面不存在

>2. Get access token
MurphySec CLI requires an access token from your MurphySec account for authentication to work properly. [What is an access token?](https://www.murphysec.com/docs/faq/access-token/)
>Go to [MurphySec platform - Access Token](https://www.murphysec.com/usr/token), click the copy button after the Token, then the access token is copied to the clipboard.

### Please read the documents below.

- [X] I've read the document [Creating a Documentation for Murphysec](https://www.murphysec.com/docs/quick-start/setup/)

**Comment by CN-You** [comment]
感谢反馈，无法访问的链接已经修正
