### ISSUE TITLE
插件token报校验异常

### ISSUE THREAD

**Issue by duzhenming** [murphysecurity/murphysec#18]
按照此步骤https://www.murphysec.com/docs/integrations/murphysec-jetbrains-plugin/#%E9%85%8D%E7%BD%AE%E6%8F%92%E4%BB%B6 操作显示token校验异常

**Comment by chncaption** [comment]
网络是通的吗，大佬，要不加下我们readme下面的运营同学的微信，我们给你解决下。

**Comment by duzhenming** [comment]
> 网络是通的吗，大佬，要不加下我们readme下面的运营同学的微信

**Comment by duzhenming** [comment]
> 网络是通的吗，大佬，要不加下我们readme下面的运营同学的微信，我们给你解决下。

在内网环境开发，不确定校验所用网址是否通，可以把请求地址发出来吗？
