### ISSUE TITLE
展示内容不准确

### ISSUE THREAD

**Issue by jiangxincode** [murphysecurity/murphysec#20]
![image](https://user-images.githubusercontent.com/5327122/167291067-1f4ab8a3-7409-47a0-a90d-e4ecc7aaf82d.png)

**Comment by chncaption** [comment]
@jiangxincode 你这个是老任务吧，我看是1月份的，我们联系您看看具体情况，如果您有需要的话，可以再扫一次。现在应该不会出现这个问题了
