### ISSUE TITLE
希望能输出全量的项目依赖信息

### ISSUE THREAD

**Issue by l0ners** [murphysecurity/murphysec#22]
有个小小的建议，希望增加一个参数，能直接在本地输出扫描项目全量的SBOM。感谢

**Comment by chncaption** [comment]
收到，感谢反馈，我们考虑下，在后面的版本加上。我找我们运营联系你看下具体的场景哈

**Comment by l0ners** [comment]
> 收到，谢谢反馈，我们考虑下，在后面的版本加上。哈我找我们运营联系你看下具体的场景

好的，谢谢回复。具体场景就是比如说昨天fastjson的漏洞，如果在漏洞库没有及时更新的情况下，想找到所有低于1.2.83版本的fastjson组件，就需要全量的SBOM列表
