### ISSUE TITLE
感觉没什么用

### ISSUE THREAD

**Issue by 2catycm** [murphysecurity/murphysec#23]
检测了好几个项目，得到的结论都是很安全，没有漏洞

**Comment by CN-You** [comment]
有可能是因为环境的原因导致检测失败了，我们邮件联系您看下具体的情况

**Comment by 2catycm** [comment]
> 有可能是因为环境的原因导致检测失败了，我们邮件联系您看下具体的情况

嗯嗯，感觉其实确实是安全的。我检测是最近写的几个小的安卓项目，看了一下你们文档，好像你们这个工具就是检查项目依赖的包的这个版本有没有发现过漏洞，然后我检测项目没有用到这些库，所以没有漏洞。
感谢大佬回复

**Comment by CN-You** [comment]
> > 有可能是因为环境的原因导致检测失败了，我们邮件联系您看下具体的情况
> 
> 嗯嗯，感觉其实确实是安全的。我检测是最近写的几个小的安卓项目，看了一下你们文档，好像你们这个工具就是检查项目依赖的包的这个版本有没有发现过漏洞，然后我检测项目没有用到这些库，所以没有漏洞。 感谢大佬回复

好的，如果之后您遇到任何工具上的使用问题，可以随时提交issues，或者直接添加readme里面我们运营的微信进行反馈，感谢。
