### ISSUE TITLE
尊重下隐私好不？

### ISSUE THREAD

**Issue by jjeffcaii** [murphysecurity/murphysec#26]
别随随便便乱检测，乱爬贡献者邮箱，乱发邮件可以么？贵司这种行为很不明智，很惹人讨厌。Github的安全检测至少人家不会乱发你邮件，你有主动权去开启，各种提醒也会尊重owner的意见。

没有道德的码农，跟蛆虫有什么区别？

**Comment by CN-You** [comment]
您好，收到您的反馈，已经通过邮件联系您了。
