### ISSUE TITLE
扫描的非真实依赖版本

### ISSUE THREAD

**Issue by sunstarsss** [murphysecurity/murphysec#45]
项目使用dependencyManagement统一管理版本号，但扫描的时候仍然会将其他依赖包的其它版本扫描出来，最典型的就是fastjson扫描出来6个版本，但实际使用的版本1.2.83

**Comment by CN-You** [comment]
收到您的反馈，我们看下

**Comment by Claire887** [comment]
@sunstarsss 哈喽 方便添加我们的联系方式嘛，一块排查下这个问题。这个项目的下方有我们的联系方式https://github.com/murphysecurity/murphysec

**Comment by sunstarsss** [comment]
来信已收到 谢谢
