### ISSUE TITLE
gitlab支持么？

### ISSUE THREAD

**Issue by noshenxian** [murphysecurity/murphysec#57]
后续有计划支持gitlab么？

**Comment by CN-You** [comment]
您好，GitLab后续有计划支持，我们联系您了解下具体的情况

**Comment by CN-You** [comment]
> 

@noshenxian 通过GitHub主页的 gmail 邮箱联系您了

**Comment by xuxiaowei-com-cn** [comment]
https://hub.docker.com/r/xuxiaoweicomcn/murphysec
JDK 8/11 项目 GitLab Runner 集成：https://gitlab.com/xuxiaowei-cloud/xuxiaowei-cloud/-/blob/main/.gitlab-ci.yml
JDK 17 项目 GitLab Runner 集成：https://gitlab.com/xuxiaowei-cloud/xuxiaowei-cloud-next/-/blob/main/.gitlab-ci.yml
