### ISSUE TITLE
子模块同时存在 Maven 与 Node 时，未能正确识别

### ISSUE THREAD

**Issue by xuxiaowei-com-cn** [murphysecurity/murphysec#6]
![20220401-17-24-42-DESKTOP-8E6LUNV-176-chrome-dXpOYvAFzE](https://user-images.githubusercontent.com/46893436/161236168-3ff4658a-7f6d-42f4-8d18-d56db85d46a7.png)
![20220401-17-25-40-DESKTOP-8E6LUNV-177-chrome-SD3dAnyabx](https://user-images.githubusercontent.com/46893436/161236191-b4496027-2914-4188-b9ed-124aa9fd15bb.png)

**Comment by xuxiaowei-com-cn** [comment]
项目地址：https://github.com/xuxiaowei-cloud/xuxiaowei-cloud

**Comment by CN-You** [comment]
感谢反馈，此问题将在下个版本解决

**Comment by xuxiaowei-com-cn** [comment]
收到

**Comment by CN-You** [comment]
v1.5.1版本发布，此问题已解决 

https://github.com/murphysecurity/murphysec/releases/tag/v1.5.1
