### ISSUE TITLE
idea 插件提示建议

### ISSUE THREAD

**Issue by iohao** [murphysecurity/murphysec#67]
<img width="626" alt="image" src="https://user-images.githubusercontent.com/26356013/192257624-f7ffc15e-13d9-4aad-abe0-31491c85208e.png">

一个提示小建议，常规思维会认为 “安全风险分数” 是 100 分为满分；

前面加个安全会容易误导人，建议改为风险分数，这样分越高就知道风险数值越大；

**Comment by CN-You** [comment]
非常感谢您的建议，这个问题已经在我们迭代的计划中
