### ISSUE TITLE
[Feature] 接口查询扫描结果solutions字段为空

### ISSUE THREAD

**Issue by xxddpac** [murphysecurity/murphysec#73]
### Search before asking

- [X] I had searched in the [issues](https://github.com/murphysecurity/murphysec/issues) and found no similar issues.

### Description

在测试时发现控制台可以显示对应组件的缺陷修复方案
![image](https://user-images.githubusercontent.com/52097208/192973949-60a3631d-e6f7-4ce6-92b6-06ac43784301.png)
但是本地调用接口该修复方案字段为空
![image](https://user-images.githubusercontent.com/52097208/192976512-a2802f18-9b08-4316-a910-67c36b16b289.png)

如果存储扫描结果，该字段的作用还是比较重要的

### Are you willing to submit PR?

- [x] #76

**Comment by iseki0** [comment]
我看看

**Comment by iseki0** [comment]
这个，你是抓了接口数据看的吗，CLI似乎没有输出这个数据的功能

**Comment by iseki0** [comment]
代码方便提供下吗，我们复现下

**Comment by xxddpac** [comment]
> 这个，你是抓了接口数据看的吗，CLI似乎没有输出这个数据的功能

CLI测试的时候加了个结果打印
![image](https://user-images.githubusercontent.com/52097208/192979463-1d1e67b4-9bb8-4e70-ae9c-1fadf2c18335.png)
这里的结果也看的solutions为空切片，一开始可能以为是结构体解析有误，所以在浏览器直接通过typeId查询，发现返回的数据solutions也是空的

**Comment by iseki0** [comment]
嗯，我这边看了下，可能是这个输出一直没用上（这个输出本来是给IDEA插件用的），所以后端就没输出，我和后端核实下
