### ISSUE TITLE
IDEA 插件，内容过多时，无Y轴滚动条

### ISSUE THREAD

**Issue by xuxiaowei-com-cn** [murphysecurity/murphysec#8]
![image](https://user-images.githubusercontent.com/46893436/162145715-7bf974f7-c255-43e0-b564-c1c37e8a33cd.png)
![image](https://user-images.githubusercontent.com/46893436/162145956-e6f3c152-5bc4-4e98-b594-af6c587e31fb.png)

**Comment by xuxiaowei-com-cn** [comment]
图一为完整内容，图二应添加Y轴滚动条

**Comment by CN-You** [comment]
感谢反馈，此功能将在 IDE 插件下个版本（v2.0.7）支持。
